name: RELEASE

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

concurrency:
  group: docker-build-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

env:
  GO_VERSION: "1.24.4"
  REGISTRY: ghcr.io

jobs:
  docker-build-and-push:
    if: >
      ${{
        github.event.pull_request.merged == true &&
        startsWith(github.event.pull_request.head.ref, 'release/v')
      }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - name: Checkout main (post-merge)
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Determine platform/arch
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Compute VERSION from head branch
        run: |
          set -euo pipefail
          BRANCH="${{ github.event.pull_request.head.ref }}"
          # Extract the version by removing 'release/v' prefix
          VERSION="${BRANCH#release/v}"
          # Validate that extraction worked correctly
          if [[ -z "${VERSION}" || "${VERSION}" == "${BRANCH}" ]]; then
            echo "Error: can't extract VERSION from '${BRANCH}' (expecting prefix 'release/v')." >&2
            exit 1
          fi
          # Export the version as environment variable for later steps
          echo "VERSION=${VERSION}" >> "$GITHUB_ENV"
          echo "Extracted VERSION=${VERSION}"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Setup Protoc
        uses: arduino/setup-protoc@v3

      - name: Install Go protobuf plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          # Add Go bin directory to PATH for global access
          echo "$HOME/go/bin" >> "$GITHUB_PATH"

      - name: Build with Makefile
        run: |
          set -euo pipefail
          make build-target
        env:
          VERSION: ${{ env.VERSION }}

      - name: Apply execution permissions
        run: chmod +x build/* || true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ env.PLATFORM_PAIR }}
          path: build/*

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU (for cross-platform emulation)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

  tag-and-release:
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    if: success()
    steps:
      - name: Checkout main (post-merge)
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Compute VERSION from head branch
        run: |
          set -euo pipefail
          VERSION="0.0.1"
          echo "VERSION=${VERSION}" >> "$GITHUB_ENV"
          echo "Extracted VERSION=${VERSION}"

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: build-artifacts
          pattern: build-linux-*

      - name: Create Git Tag
        run: |
          set -e
          # Configure git identity for tagging
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Create and push the version tag (ignore if already exists)
          git tag "v${VERSION}" || true
          git push origin "v${VERSION}" || true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: |
            🎉 Release **v${{ env.VERSION }}**
          files: build-artifacts/*/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}